package:
  name: scipy
  version: 1.1.0

source:
  url: https://files.pythonhosted.org/packages/07/76/7e844757b9f3bf5ab9f951ccd3e4a8eed91ab8720b0aac8c2adcc2fdae9f/scipy-1.1.0.tar.gz
  sha256: 878352408424dffaa695ffedf2f9f92844e116686923ed9aa8626fc30d32cfd1

build:
  cflags: -ICLAPACK-WA/F2CLIBS/libf2c/ -Wno-implicit-function-declaration
  cxxflags:

requirements:
  run:
    - numpy
